SOURCES = {
    "postcodes_io": {
        "publisher": "Postcodes.io / ONS-linked geography",
        "title": "Postcode geography lookup",
        "landing_url": "https://postcodes.io/",
        "licence_name": "See source terms",
        "attribution_text": None,
        "refresh_policy": "quarterly/check-on-demand",
    },
    "police_uk": {
        "publisher": "Police.uk / Home Office open data",
        "title": "Street-level crime",
        "landing_url": "https://data.police.uk/",
        "licence_name": "Open data — verify current source terms",
        "attribution_text": None,
        "refresh_policy": "monthly",
    },
    "ea_flood_monitoring": {
        "publisher": "Environment Agency",
        "title": "Flood monitoring API",
        "landing_url": "https://environment.data.gov.uk/flood-monitoring/doc/reference",
        "licence_name": "Open Government Licence",
        "attribution_text": None,
        "refresh_policy": "live",
    },
    "ofsted_schools": {
        "publisher": "Ofsted",
        "title": "State-funded school inspection outcomes",
        "landing_url": "https://www.gov.uk/government/statistical-data-sets/monthly-management-information-ofsteds-school-inspections-outcomes",
        "licence_name": "Verify current dataset terms before production use",
        "attribution_text": None,
        "refresh_policy": "monthly",
    },
    "hmlr_ppd": {
        "publisher": "HM Land Registry",
        "title": "Price Paid Data",
        "landing_url": "https://www.gov.uk/government/statistical-data-sets/price-paid-data-downloads",
        "licence_name": "Open Government Licence v3.0",
        "attribution_text": "Contains HM Land Registry data © Crown copyright and database right 2021. This data is licensed under the Open Government Licence v3.0.",
        "refresh_policy": "monthly",
    },
    "ons_pipr_hpi": {
        "publisher": "Office for National Statistics",
        "title": "Private rent and house prices, UK",
        "landing_url": "https://www.ons.gov.uk/economy/inflationandpriceindices/bulletins/privaterentandhousepricesuk/latest",
        "licence_name": "ONS / Open Government Licence — verify current terms",
        "attribution_text": None,
        "refresh_policy": "monthly",
    },
    "ea_long_term_flood": {
        "publisher": "Environment Agency",
        "title": "Long-term flood risk by postcode",
        "landing_url": "https://environment.data.gov.uk/flood-risk-postcode-tool",
        "licence_name": "Open Government Licence",
        "attribution_text": None,
        "refresh_policy": "monthly-release-check",
    },
}
